require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ToDoItemsController do

  # This should return the minimal set of attributes required to create a valid
  # ToDoItem. As you add validations to ToDoItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "project" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ToDoItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all to_do_items as @to_do_items" do
      to_do_item = ToDoItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:to_do_items).should eq([to_do_item])
    end
  end

  describe "GET show" do
    it "assigns the requested to_do_item as @to_do_item" do
      to_do_item = ToDoItem.create! valid_attributes
      get :show, {:id => to_do_item.to_param}, valid_session
      assigns(:to_do_item).should eq(to_do_item)
    end
  end

  describe "GET new" do
    it "assigns a new to_do_item as @to_do_item" do
      get :new, {}, valid_session
      assigns(:to_do_item).should be_a_new(ToDoItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested to_do_item as @to_do_item" do
      to_do_item = ToDoItem.create! valid_attributes
      get :edit, {:id => to_do_item.to_param}, valid_session
      assigns(:to_do_item).should eq(to_do_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ToDoItem" do
        expect {
          post :create, {:to_do_item => valid_attributes}, valid_session
        }.to change(ToDoItem, :count).by(1)
      end

      it "assigns a newly created to_do_item as @to_do_item" do
        post :create, {:to_do_item => valid_attributes}, valid_session
        assigns(:to_do_item).should be_a(ToDoItem)
        assigns(:to_do_item).should be_persisted
      end

      it "redirects to the created to_do_item" do
        post :create, {:to_do_item => valid_attributes}, valid_session
        response.should redirect_to(ToDoItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved to_do_item as @to_do_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToDoItem.any_instance.stub(:save).and_return(false)
        post :create, {:to_do_item => { "project" => "invalid value" }}, valid_session
        assigns(:to_do_item).should be_a_new(ToDoItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToDoItem.any_instance.stub(:save).and_return(false)
        post :create, {:to_do_item => { "project" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested to_do_item" do
        to_do_item = ToDoItem.create! valid_attributes
        # Assuming there are no other to_do_items in the database, this
        # specifies that the ToDoItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ToDoItem.any_instance.should_receive(:update).with({ "project" => "" })
        put :update, {:id => to_do_item.to_param, :to_do_item => { "project" => "" }}, valid_session
      end

      it "assigns the requested to_do_item as @to_do_item" do
        to_do_item = ToDoItem.create! valid_attributes
        put :update, {:id => to_do_item.to_param, :to_do_item => valid_attributes}, valid_session
        assigns(:to_do_item).should eq(to_do_item)
      end

      it "redirects to the to_do_item" do
        to_do_item = ToDoItem.create! valid_attributes
        put :update, {:id => to_do_item.to_param, :to_do_item => valid_attributes}, valid_session
        response.should redirect_to(to_do_item)
      end
    end

    describe "with invalid params" do
      it "assigns the to_do_item as @to_do_item" do
        to_do_item = ToDoItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToDoItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => to_do_item.to_param, :to_do_item => { "project" => "invalid value" }}, valid_session
        assigns(:to_do_item).should eq(to_do_item)
      end

      it "re-renders the 'edit' template" do
        to_do_item = ToDoItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToDoItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => to_do_item.to_param, :to_do_item => { "project" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested to_do_item" do
      to_do_item = ToDoItem.create! valid_attributes
      expect {
        delete :destroy, {:id => to_do_item.to_param}, valid_session
      }.to change(ToDoItem, :count).by(-1)
    end

    it "redirects to the to_do_items list" do
      to_do_item = ToDoItem.create! valid_attributes
      delete :destroy, {:id => to_do_item.to_param}, valid_session
      response.should redirect_to(to_do_items_url)
    end
  end

end
